[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'zenlang/zen.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
